version: "3.9"
services:
  opifolio:
    container_name: opifiolio
    image: opifolio
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - PORT=80
    restart: unless-stopped